name: Make Beta Release

on:
  push:
    branches:
      - 'beta'
    paths:
      - '.github/edit2MakeNewBeta'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Source Code Download
        run: git clone --branch beta --single-branch --recurse-submodules https://github.com/DHD2280/Oxygen-Customizer.git .

      - name: JDK 17 Setup
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Shell Scripts Permissions
        run: chmod +x .github/*.sh

      - name: Changelog Generation
        run: .github/extractChanges.sh

      - name: Version Bump
        run: .github/bumpVersion.sh ${{ github.run_id }}

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Signature files preparation
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Gradle Build
        run: ./gradlew assembleRelease

      - name: Upload Xposed Artifact to Actions
        uses: actions/upload-artifact@v4.3.1
        with:
          name: OxygenCustomizer
          path: app/build/outputs/apk/release/*.apk

      - name: Oxygen Customizer Binary Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: 'beta_builds'
          name: 'Latest Beta'
          omitBodyDuringUpdate: true
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          artifacts: 'app/build/outputs/apk/release/*.apk'

      - name: Version Bump Commit
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'beta'
          commit-message: 'Version update: Release'
          force-add: 'true'
          files: app/build.gradle.kts BetaChangelog.md latestBeta.json
          name: GitHub
          email: OxygenCustomizer@dhd.it

      - name: Telegram Channel Post
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.OC_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TK }}
          message: ${{ env.TMessage }}
          format: markdown

      - name: Telegram Channel Post
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.OC_CHANNEL2 }}
          token: ${{ secrets.TELEGRAM_TK }}
          message: ${{ env.TMessage }}
          format: markdown

      - name: Zip artifact for deployment
        run: cd ./app/build/outputs/apk/release/ && zip OxygenCustomizer.zip *.apk -r

      - name: Telegram File Attachment
        run: |
          curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TK }}/sendMediaGroup?chat_id=${{ secrets.OC_CHANNEL }}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FXposed%22%7D%5D" -F Xposed="@app/build/outputs/apk/release/OxygenCustomizer.zip"

      - name: Telegram File Attachment
        run: |
          curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TK }}/sendMediaGroup?chat_id=${{ secrets.OC_CHANNEL2 }}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FXposed%22%7D%5D" -F Xposed="@app/build/outputs/apk/release/OxygenCustomizer.zip"
